TARGET = rtm-gwas-snpldb

CXX := clang++

CXXFLAGS := -O2 -std=c++11 -fopenmp
LDFLAGS  := -fopenmp -L/usr/local/lib

OBJ := $(patsubst %.cpp,%.o,$(wildcard src/*.cpp))

$(TARGET): $(OBJ)
	$(CXX) $(LDFLAGS) -o $@ $?

.PHONY: clean
clean:
	$(RM) $(OBJ) $(TARGET)
