TARGET = rtm-gwas-gsc

RTM_GWAS_VERSION ?= $(shell cat ../VERSION)
DEFINES := -DRTM_GWAS_VERSION=\"$(RTM_GWAS_VERSION)\"

CC  := clang
CXX := clang++

CFLAGS   := -O2 -std=c11 -fopenmp
CXXFLAGS := -O2 -std=c++11 -fopenmp $(DEFINES) -I/usr/local/include
LDFLAGS  := -fopenmp -L/usr/local/lib
LDLIBS   := -framework Accelerate

OBJ := $(patsubst %.c,%.o,$(wildcard src/*.c))
OBJ += $(patsubst %.cpp,%.o,$(wildcard src/*.cpp))

$(TARGET): $(OBJ)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)

.PHONY: clean
clean:
	$(RM) $(OBJ) $(TARGET)
