TARGET  := rtm-gwas.exe
HOST    := win32

CC       := i686-w64-mingw32-gcc
CXX      := i686-w64-mingw32-g++
CFLAGS   := -O2 -Wall -DNDEBUG
CXXFLAGS := -O2 -Wall -DNDEBUG -std=c++11 -fopenmp
LDFLAGS  := -s -static -Ldeps/Rmath-$(HOST) -Ldeps/OpenBLAS-$(HOST)
LDLIBS   := -lRmath -lopenblas -lgfortran -lquadmath -lgomp

OBJECTS := $(patsubst %.cpp,%.o,$(wildcard src/*.cpp)) src/zeroin.o

.PHONY: all clean

all: $(TARGET)

clean:
	$(RM) $(OBJECTS) $(TARGET)*

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) $(CXXFLAGS) $(LDFLAGS) $(LDLIBS) -o $@
