TARGET  := rtm-gwas
HOST    := osx64

CC       := gcc
CXX      := g++
CFLAGS   := -O2 -Wall -DNDEBUG
CXXFLAGS := -O2 -Wall -DNDEBUG -std=c++11
LDFLAGS  := -Ldeps/Rmath-$(HOST) -Ldeps/OpenBLAS-$(HOST)
LDLIBS   := -lRmath -lopenblas /usr/local/lib/libgfortran.a /usr/local/lib/libquadmath.a \
            /usr/local/lib/gcc/x86_64-apple-darwin14.0.0/4.9.2/libgcc.a

OBJECTS := $(patsubst %.cpp,%.o,$(wildcard src/*.cpp)) src/zeroin.o

.PHONY: all clean

all: $(TARGET)

clean:
	$(RM) $(OBJECTS) $(TARGET)*

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) $(CXXFLAGS) $(LDFLAGS) $(LDLIBS) -o $@
